### PR TITLE
Changes to the template. 

### PR DESCRIPTION
**Pull request by skymen**
Added a column for c3runtime and added a category header line to divide features in categories later

### CODE REVIEW

**Comment by Armaldio** [comment]
Can you please update the example according? (add third cell and more relevant example)

**Comment by Armaldio** [comment]
Also, is it really relevant to have the c2runtime since it's going to be deprecated and mostly only transitioning users are using it?

**Comment by skymen** [comment]
I guess we could just specify if a feature is only available on c3runtime and keep C3 as a single column yeah

**Comment by Armaldio** [comment]
Are you OK with the changes i made ?

**Comment by skymen** [comment]
Yeah ok 👌

**Pull request merged**
